# Generated by Django 2.2.19 on 2023-02-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_needed', models.CharField(max_length=100, verbose_name='Что нужно сделать (кратко)')),
                ('urgency', models.CharField(choices=[('week', 'В течении недели'), ('day', 'В течении дня'), ('hour', 'В течении часа'), ('now', 'Срочно'), ('yesterday', 'Бросать все, делать это')], default='day', max_length=150)),
                ('description', models.CharField(max_length=350, verbose_name='Что нужно сделать (подробно)')),
            ],
        ),
    ]
