# Generated by Django 2.2.19 on 2023-02-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_needed', models.CharField(max_length=100, unique=True, verbose_name='Что нужно сделать (кратко)')),
                ('type', models.CharField(choices=[('send', 'Отправка материалов'), ('receive', 'Получение материалов'), ('transport', 'Перемещение материалов внутри студии'), ('patch', 'Переделать/Изменить материалы'), ('other', 'Другое')], default='receive', max_length=150, verbose_name='Тип задачи')),
                ('urgency', models.CharField(choices=[('week', 'В течении недели'), ('day', 'В течении дня'), ('hour', 'В течении часа'), ('now', 'Срочно'), ('yesterday', 'Бросать все, делать это')], default='day', max_length=150, verbose_name='Срочность')),
                ('description', models.CharField(max_length=350, null=True, verbose_name='Что нужно сделать (подробно)')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('finished', 'Завершено'), ('not_viewed', 'Не просмотрено')], default='not_viewed', max_length=150, verbose_name='Статус')),
                ('comments', models.CharField(max_length=350, null=True, verbose_name='Комментарий исполнителя')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.Project', verbose_name='Проект')),
            ],
        ),
    ]
