# Generated by Django 2.2.19 on 2023-02-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20230211_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В работе'), ('finished', 'Завершено'), ('not_viewed', 'Не просмотрено')], default='not_viewed', max_length=150, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('send', 'Отправка материалов'), ('receive', 'Получение материалов'), ('transport', 'Перемещение материалов внутри студии'), ('patch', 'Переделать/Изменит материалы'), ('other', 'Другое')], default='receive', max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='what_needed',
            field=models.CharField(max_length=100, unique=True, verbose_name='Что нужно сделать (кратко)'),
        ),
    ]
