# Generated by Django 2.2.19 on 2023-02-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20230211_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.CharField(max_length=350, null=True, verbose_name='Комментарий исполнителя'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.Project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('send', 'Отправка материалов'), ('receive', 'Получение материалов'), ('transport', 'Перемещение материалов внутри студии'), ('patch', 'Переделать/Изменить материалы'), ('other', 'Другое')], default='receive', max_length=150, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.CharField(choices=[('week', 'В течении недели'), ('day', 'В течении дня'), ('hour', 'В течении часа'), ('now', 'Срочно'), ('yesterday', 'Бросать все, делать это')], default='day', max_length=150, verbose_name='Срочность'),
        ),
    ]
