# Generated by Django 3.2.18 on 2023-02-25 12:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 12, 48, 12, 751842, tzinfo=utc), verbose_name='Время создания задачи'),
        ),
    ]
