# Generated by Django 2.2.19 on 2023-02-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20230213_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=350, null=True, verbose_name='Что нужно сделать (подробно)'),
        ),
    ]
