# Generated by Django 3.2.18 on 2023-02-25 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания задачи'),
        ),
    ]
